<?php

$links[] = array('type' => 'text/css', 'href' => $skin_iri . 'demo.css', 'rel' => 'stylesheet');

require(dirname(__FILE__) . '/header.php');

?>

<div id="blq-content" class="blq-typ">
	 <h1><?php e($page_title); ?></h1>
</div>

<?php echo $form->render($request);

echo '<div class="demo-wsurl">';
echo '<p>URL for this webservice request:<br /> <code><a href="' . _e($blq->url) . '">' . str_replace('&amp;', '<br />&amp;', _e($blq->url)) . '</a></code></p>';
echo '</div>';

?>

<?php

require(dirname(__FILE__) . '/footer.php');
